# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messageBoxG.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Systeme_de_coordonnees(object):
    def setupUi(self, Systeme_de_coordonnees):
        Systeme_de_coordonnees.setObjectName("Systeme_de_coordonnees")
        Systeme_de_coordonnees.resize(311, 121)
        Systeme_de_coordonnees.setMinimumSize(QtCore.QSize(311, 121))
        Systeme_de_coordonnees.setMaximumSize(QtCore.QSize(311, 121))
        self.label = QtWidgets.QLabel(Systeme_de_coordonnees)
        self.label.setGeometry(QtCore.QRect(10, 50, 131, 16))
        self.label.setObjectName("label")
        self.lineEditX = QtWidgets.QLineEdit(Systeme_de_coordonnees)
        self.lineEditX.setGeometry(QtCore.QRect(150, 50, 41, 21))
        self.lineEditX.setMaxLength(5)
        self.lineEditX.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditX.setObjectName("lineEditX")
        self.label_2 = QtWidgets.QLabel(Systeme_de_coordonnees)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 81, 31))
        self.label_2.setObjectName("label_2")
        self.checkBoxRepereActif = QtWidgets.QCheckBox(Systeme_de_coordonnees)
        self.checkBoxRepereActif.setGeometry(QtCore.QRect(110, 20, 32, 17))
        self.checkBoxRepereActif.setMinimumSize(QtCore.QSize(32, 17))
        self.checkBoxRepereActif.setMaximumSize(QtCore.QSize(32, 17))
        self.checkBoxRepereActif.setText("")
        self.checkBoxRepereActif.setChecked(False)
        self.checkBoxRepereActif.setObjectName("checkBoxRepereActif")
        self.lineEditY = QtWidgets.QLineEdit(Systeme_de_coordonnees)
        self.lineEditY.setGeometry(QtCore.QRect(210, 49, 41, 21))
        self.lineEditY.setMaxLength(5)
        self.lineEditY.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditY.setObjectName("lineEditY")
        self.lineEditZ = QtWidgets.QLineEdit(Systeme_de_coordonnees)
        self.lineEditZ.setGeometry(QtCore.QRect(270, 50, 41, 20))
        self.lineEditZ.setMaxLength(5)
        self.lineEditZ.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditZ.setObjectName("lineEditZ")
        self.label_3 = QtWidgets.QLabel(Systeme_de_coordonnees)
        self.label_3.setGeometry(QtCore.QRect(140, 50, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Systeme_de_coordonnees)
        self.label_4.setGeometry(QtCore.QRect(200, 50, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Systeme_de_coordonnees)
        self.label_5.setGeometry(QtCore.QRect(260, 50, 16, 20))
        self.label_5.setObjectName("label_5")
        self.pushButtonOK = QtWidgets.QPushButton(Systeme_de_coordonnees)
        self.pushButtonOK.setGeometry(QtCore.QRect(70, 90, 75, 23))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.pushButtonAnnuler = QtWidgets.QPushButton(Systeme_de_coordonnees)
        self.pushButtonAnnuler.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.pushButton = QtWidgets.QPushButton(Systeme_de_coordonnees)
        self.pushButton.setGeometry(QtCore.QRect(164, 10, 111, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Systeme_de_coordonnees)
        QtCore.QMetaObject.connectSlotsByName(Systeme_de_coordonnees)

    def retranslateUi(self, Systeme_de_coordonnees):
        _translate = QtCore.QCoreApplication.translate
        Systeme_de_coordonnees.setWindowTitle(_translate("Systeme_de_coordonnees", "Système de coordonnées"))
        self.label.setText(_translate("Systeme_de_coordonnees", "Coordonnéés du repère"))
        self.label_2.setText(_translate("Systeme_de_coordonnees", "Repère activé:"))
        self.label_3.setText(_translate("Systeme_de_coordonnees", "X"))
        self.label_4.setText(_translate("Systeme_de_coordonnees", "Y"))
        self.label_5.setText(_translate("Systeme_de_coordonnees", "Z"))
        self.pushButtonOK.setText(_translate("Systeme_de_coordonnees", "OK"))
        self.pushButtonAnnuler.setText(_translate("Systeme_de_coordonnees", "Annuler"))
        self.pushButton.setText(_translate("Systeme_de_coordonnees", "position courante"))
