"""Dialog displaying the textual reports generated by the controller."""

from PyQt5.QtWidgets import QMainWindow

from ..forms.reports_ui import Ui_Form


class Rapports(QMainWindow, Ui_Form):
	def __init__(self, rapport):
		super(Rapports, self).__init__()
		self.setupUi(self)
		self.rapport=rapport
		self.plainTextEdit.insertPlainText(self.rapport)
